import { combineReducers } from "redux";
import location from "./location";
import theme from "./theme";
import animal from "./animal";
import breed from "./breed";

// We can replace our hand-written rootReducer with a shorter one generated by combineReducers
export default combineReducers({
  location,
  theme,
  animal,
  breed,
});
